### ISSUE TITLE
Skeleton missing?

### ISSUE THREAD

**Issue by Knito58** [ItziSpyder/Impropers3DMinimap#2]
MC 1.21 Fabric
Improper's 3D Minimap 1.21-0.0.3

The skeleton rattles behind the wall but I cannot "see" it with the 3d map. I can configure zombies to be seen but the skeleton entry seems to be missing.

Am I right? I tried to find the skeleton in the list but didn't find it on multiple occasions.

**Comment by ItziSpyder** [comment]
Would you mind providing a screenshot of the skeleton entry being selected, and another one of the skeleton not appearing on the radar? Thanks

**Comment by Knito58** [comment]
No Sir - I did not find the skeleton entry in the list of the GUI. I'm too blind to see the skeleton entry. Where is it? I searched for it multiple times now and did not find it.

**Comment by ItziSpyder** [comment]
> No Sir - I did not find the skeleton entry in the list of the GUI. I'm too blind to see the skeleton entry. Where is it? I searched for it multiple times now and did not find it.

What do you mean? 
![image](https://github.com/user-attachments/assets/cd97bb96-6821-4477-aead-016fd4ab0b8f)

**Comment by Knito58** [comment]
Thank you very much. I was blind but now can see.
